[sinks.gcp_gcs]
  # General
  type = "gcp_cloud_storage" 
  inputs = ["log_json"]
  bucket = "${GCS_BUCKET}" 
  credentials_path = "/var/secrets/GOOGLE_APPLICATION_CREDENTIALS.json"
  compression = "gzip" 
  framing.method = "newline_delimited"
  encoding.codec = "json"
  key_prefix = "{{fly.app.name}}/%F/" # optional, default
  healthcheck.enabled = true # optional, default

